### ISSUE TITLE
Chorus should be a synth-wide thing, not using `OSCS-1`

### ISSUE THREAD

**Issue by bwhitman** [bwhitman/amy#101]
Chorus v2 will let you set “depth” aka mix aka level, “amp”, “freq”  and “max_delay." (We discussed maybe letting waveform be changed, but SAW seems ok for now.) 

We keep the chorus osc around as a separate individual thing and address it using 4 args, two of them are new. `OSCS-1` is now useable for anything else.

**Comment by dpwe** [comment]
"depth" should be how deeply modulated the delay is, i.e. the amplitude of the delay-modulating oscillator. 

"level" should be how much chorus is added in to the final output, i.e. the gain factor applied to the output of the chorus delay.

**Comment by bwhitman** [comment]
"Depth" is current level? And "level" is current osc amp?

**Comment by dpwe** [comment]
Current chorus.level is mix
level, aka "level".  

Depth is currently controlled by the output amplitude of the chorus control oscillator 119 (osc=119, amp=X). It should become chorus.depth.

**Comment by bwhitman** [comment]
We confirmed we resolved this in the `junopatches` branch. will come out when we merge that
