### ISSUE TITLE
Unexpected delay between event and audio.

### ISSUE THREAD

**Issue by octetta** [bwhitman/amy#21]
On Fedora 37 (now using PulseAudio), with `amy-example`, there's a noticeable (~3 second) delay between when events are sent and when AMY starts generating audio.

The same behavior is not seen on macOS+coreAudio.

I'll dig into this but wanted to note, because this wasn't expected.

**Comment by dpwe** [comment]
Maybe relevant:
https://askubuntu.com/questions/218444/sound-output-starts-delayed

**Comment by octetta** [comment]
Thanks to you both for putting up with my nonsense... this project is very exciting to me. Hits a lot of sweet spots that libpd, and other software systems I've tinkered with don't.
Working on a simplistic "port driver" for Erlang/Elixir that will probably use your very nice ASCII protocol.

**Comment by octetta** [comment]
Using miniaudio library seems to remove the latency introduced by libsoundio + PulseAudio.
