### ISSUE TITLE
Linux audio and WASM audio output frequencies are out-of-tune

### ISSUE THREAD

**Issue by octetta** [bwhitman/amy#28]
Via my Fender phone tuning app:

- `amy-message` with `v0w0n69l1` on Linux + miniaudio shows 440.1 Hz
- `amy.wasm` (via a web app I've yet to generate a PR for) with `v0w0n69l1` on Linux + FireFox 110.1 shows 479.0 Hz

I'll hook up a scope to get a more accurate numbers, and can test on other browsers and platforms for metrics

If this is an unavoidable consequence of using `amy.wasm` might we introduce a global tuning parameter akin to the global volume setting?

Happy to keep helping, as I'm quite intrigued with AMY.

**Comment by dpwe** [comment]
Amy’s timing depends on the audio sample rate. It sounds like the wasm is
writing to a 48kHz DAC. Can you control that?

  DAn.

**Comment by octetta** [comment]
> Amy’s timing depends on the audio sample rate. It sounds like the wasm is writing to a 48kHz DAC. Can you control that? 

Oh my gosh, the ratio the two should have been my first clue on this... I'll look at this closer, but think you've found the root cause.

**Comment by bwhitman** [comment]
I bet in index.html in the example, you could set AudioContext up with a sample rate. You should force it to whatever AMY's SAMPLE_RATE is.

**Comment by bwhitman** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/AudioContext

**Comment by octetta** [comment]
Thanks for the tips. I'm hacking at index.html and trying to understand more about what's happening inside web audio.

On FireFox + Linux, the sample rate seems to be read-only, at least by simple initialization of AudioContext, but at least I see where 48000 Hz versus 44100 Hz is happening.

I'll see what I can figure out and hopefully contribute here.

Eventually, I'll work my way around to the ESP32 / MCU side of things, but glad to play and help here too.

**Comment by octetta** [comment]
Brian accepted the change.
