### ISSUE TITLE
Noise waveform ignores frequency parameter

### ISSUE THREAD

**Issue by octetta** [bwhitman/amy#31]
Is this by design?

Should I be filtering the noise to a specific frequency I desire?

If I want to use noise as a modulator, what's the best way to achieve this?

From a math point-of-view maybe my question makes no sense.

From an old-synth-nerd point-of-view I think it does.

**Comment by dpwe** [comment]
It’s not clear what a frequency parameter should do for noise. White noise
is supposed to be flat in frequency. You probably want to put it through a
variable filter.

  DAn.

**Comment by octetta** [comment]
Makes sense. Is it possible for the filtered output as a LFO?

**Comment by octetta** [comment]
Agree that this isn't needed.

**Comment by smutax** [comment]
Hi. So was it something like "random (noise) LFO waveform" @octetta had in mind as modulation source? Like Sample & Hold LFO! Can it be achieved,  or it's not implemented at this stage? That would be very nice! Also, as feature suggestion, would be great to have osc pan as modulation destination! Cheers.

**Comment by dpwe** [comment]
I just implemented a random-value sample-and-hold modulator in the `lfosnh` branch.  So these commands:
```
amy.send(osc=1, freq=4, amp=0.1, wave=amy.NOISE)
amy.send(osc=0, wave=amy.SINE, mod_target=amy.TARGET_FREQ, mod_source=1)
amy.send(osc=0, note=64, vel=1)
```
.. will generate a sine tone whose pitch shifts randomly by a small amount 4 times a second.  Is that what you meant?

**Comment by bwhitman** [comment]
>Also, as feature suggestion, would be great to have osc pan as modulation destination

That should already exist, although I'd believe it's not documented well. TARGET_PAN should work!

**Comment by smutax** [comment]
> > Also, as feature suggestion, would be great to have osc pan as modulation destination
> 
> That should already exist, although I'd believe it's not documented well. TARGET_PAN should work!

Thanks for pointing out. Will try that. Cheers.

**Comment by smutax** [comment]
> I just implemented a random-value sample-and-hold modulator in the `lfosnh` branch. So these commands:
> 
> ```
> amy.send(osc=1, freq=4, amp=0.1, wave=amy.NOISE)
> amy.send(osc=0, wave=amy.SINE, mod_target=amy.TARGET_FREQ, mod_source=1)
> amy.send(osc=0, note=64, vel=1)
> ```
> 
> .. will generate a sine tone whose pitch shifts randomly by a small amount 4 times a second. Is that what you meant?

That might be it! I need to test and see. Thanks a lot for that @dpwe ! 👏

**Comment by octetta** [comment]
Here's a wire protocol example showing the TARGET_PAN in operation:

```
v1w0f1a1
v0w0g512L1
v0n64l1
```
