### ISSUE TITLE
Could the feedback parameter be used to signal that a waveform plays in reverse?

### ISSUE THREAD

**Issue by octetta** [bwhitman/amy#39]
Just brainstorming of features I'd like and can work on.

In the short-term, this is most relevant to me for the PCM wave-type.

**Comment by bwhitman** [comment]
That is a fun and probably easy to implement idea!

**Comment by octetta** [comment]
I did this in some very horrible ways:
- added a capture buffer to steal rendered frames
- allow moving a capture to a "user PCM" slot
- various capture manipulation, including a "reverse" function
This is a horrible hack at the moment, so I made a fork until it's a bit cleaner
See it in action @ https://youtu.be/yLpVCpF2w2I
