### ISSUE TITLE
Is this line still necessary, considering the same member is set to 0 just a few lines down?

### ISSUE THREAD

**Issue by octetta** [bwhitman/amy#42]
https://github.com/bwhitman/amy/blob/fa48eb38a6446ebd69d3350f4489379c9772e8a6/src/pcm.c#L47

**Comment by bwhitman** [comment]
Hm! Clearly not. Safe to remove. I wager this is just left over from a previous PCM approach. Nice find, thanks

**Comment by bwhitman** [comment]
This has been fixed!
